### ISSUE TITLE
Question: the relationship between SAPIENTA and SAPIENTAproject

### ISSUE THREAD

**Issue by XuperX** [ravenscroftj/SAPIENTA#1]
Dear James,

Thanks for developing this tool. I am planning to use SAPIENTA for my own literature mining. I came across the http://www.sapientaproject.com/ website. May I ask what is the relationship between this repo and that project?

If I understand correctly, the SAPIENTAproject website and code have been superseded by this repo? And this repo is currently the official one?

Thanks for your reply!

**Comment by ravenscroftj** [comment]
Hi there - thanks for your question - that's right this is the official repository for the project now. Maria has not had the opportunity to update the original site for a few years. We also have a live instance of the API that you can use here: https://sapienta.dcs.aber.ac.uk/ - again appreciate this is not currently well sign-posted. Please let me know if you have any further questions :)
